# Generated by Django 5.0.2 on 2024-02-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='Имя')),
                ('lname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('hage', models.IntegerField(verbose_name='Возраст')),
                ('passp', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['hage'],
            },
        ),
    ]
