# Generated by Django 5.0.2 on 2024-02-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='human',
            name='passp',
            field=models.CharField(max_length=15, verbose_name='Паспорт'),
        ),
        migrations.AddField(
            model_name='human',
            name='profs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Human.profession', verbose_name='Профессия'),
        ),
    ]
